// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1qcyds8JX_fjwpEQIYMVg_oxIJA6k9A',
    appId: '1:207609244450:web:3e0cd3155646794353937b',
    messagingSenderId: '207609244450',
    projectId: 'tradiverser',
    authDomain: 'tradiverser.firebaseapp.com',
    storageBucket: 'tradiverser.firebasestorage.app',
    measurementId: 'G-D50GFSSRQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS8qEWdVbaXlJm-9KDh1Q4xldyWmCHkzE',
    appId: '1:207609244450:android:4df53441e901c0f753937b',
    messagingSenderId: '207609244450',
    projectId: 'tradiverser',
    storageBucket: 'tradiverser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2MBGZhfWPFr8S5jFBd6J4W4WWkc2Wlk',
    appId: '1:207609244450:ios:f80f1c1ff9e8512b53937b',
    messagingSenderId: '207609244450',
    projectId: 'tradiverser',
    storageBucket: 'tradiverser.firebasestorage.app',
    iosClientId: '207609244450-m6u84t8v2laghufamr6t5n3c706put51.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradiverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2MBGZhfWPFr8S5jFBd6J4W4WWkc2Wlk',
    appId: '1:207609244450:ios:f80f1c1ff9e8512b53937b',
    messagingSenderId: '207609244450',
    projectId: 'tradiverser',
    storageBucket: 'tradiverser.firebasestorage.app',
    iosClientId: '207609244450-m6u84t8v2laghufamr6t5n3c706put51.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradiverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1qcyds8JX_fjwpEQIYMVg_oxIJA6k9A',
    appId: '1:207609244450:web:e4e96c3976e3f91b53937b',
    messagingSenderId: '207609244450',
    projectId: 'tradiverser',
    authDomain: 'tradiverser.firebaseapp.com',
    storageBucket: 'tradiverser.firebasestorage.app',
    measurementId: 'G-ZX9MENW1ZD',
  );
}
